swagger: '2.0'
info:
  version: '1.0.0'
  title: WayAround API
  description: WayAround API using OAuth2 Access Code Flow
  contact:
    name: Giancarlo Rhodes
    url: https://www.onshoreoutsourcing.com/
    email: giancarlo.rhodes@onshoreoutsourcing.com
 
# Under securityDefinitions we declare which security schemes can be used.
# These definitions do not affect to the operations, but can be applied
# using the 'security' key at the global level or the operation level.
# In this sample, we'll see how to apply the security definition globally,
# and override it at the operation level.
#
# Note that for Access Code Flow, you must provide the Token URL.
securityDefinitions:
  accessCode:
    type: oauth2
    # This should be updated to the Token URL of your OAuth provider.
    tokenUrl: http://example.com/oauth/token
    # This should be updated to the Authorization URL of your OAuth provider.
    authorizationUrl: http://example.com/oauth/auth
    flow: accessCode
    scopes:
      write: allows modifying resources
      read: allows reading resources

# Here we apply the security flow called 'accessCode' globally to all the operations in the spec. 
# This security scheme is defined above in the 'securityDefinitions' section.
# Global security can be overridden an operation level as seen in the example below
security:
  - accessCode:
    - read
    - write
paths:
  /account:
    # In this operation we do not apply the security, because it was applied globally above.
    # The security will be applied to this operation for that reason.
    post:
      summary: Attempt logging in with username and password
      operationId: trylogin
      description: Attempt login with form data username and password.  Exmaple http://api.wayaround.com/v1/account/trylogin
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: username
          in: formData
          description: username used in login attempt
          required: true
          type: string
        - name: password
          in: formData
          description: user password user in login attempt
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
    get:
      summary: Get the user data by query string
      operationId: getuser
      description: How does role affect this call? Global and Site Admins can get any individual. Regular User can only get their own data. Exmaple http://api.wayaround.com/v1/account/getuser?userId=123456789
      produces:
        - application/json
      parameters:
        - in: query
          name: userId
          description: pass an optional user id
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        404:
          description: User Not Found
        500:
          description: Internal Server Error
  /account/getuserbypath/{userId}:
    get:
      summary: Get the user data by path
      operationId: getuserbypath
      description: functionally the same as getuser but passing userId in path. Exmaple http://api.wayaround.com/v1/account/getuserbypath/123456789 
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: pass an optional user id in url path
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        404:
          description: User Not Found
        500:
          description: Internal Server Error
  /account/getuserroles/{userId}:        
    get:
      summary: get the user roles
      operationId: getuserroles
      description: Exmaple http://api.wayaround.com/v1/account/getuserroles/123456789
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: pass an optional user id in url path
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserRoles'
        404:
          description: User Not Found
        500:
          description: Internal Server Error
          
  /account/getuserorganizations/{userId}:        
    get:
      summary: get the user organizations
      operationId: getuserorganizations
      description: Exmaple http://api.wayaround.com/v1/account/getuserorganizations/123456789
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: pass an optional user id in url path
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserOrganizations'
        404:
          description: User Not Found
        500:
          description: Internal Server Error
  /ping:
    get:
      summary: Server heartbeat operation
      description: This operation shows how to override the global security defined above, as we want to open it up for all users.
      # We want to require no security schemes and override the globally define security scheme.
      # To do that, we simply provide an empty array to the 'security' property.
      security: [ ]
      responses:
        200:
          description: OK
definitions:
  UserRoles:
    type: object
    properties:
      roles:
        type: array
        items:
          type: object
          properties:
            rolename:
              type: string
  UserOrganizations:
    type: object
    properties:
      organizations:
        type: array
        items:
          type: object
          properties:
            organizationname:
              type: string
            organizationnid:
              type: integer
  User:
    type: object
    properties:
      userid:
        type: integer
      userName:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      roles:
        type: array
        items:
          type: object
          properties:
            role:
              type: string
host: api.wayaround.com
basePath: /v1
schemes: 
  - http
  - https
